<div class="container-fluid">
        <div class="row content">
            <div class="col-md-3 sidenav">
                <h4>Página de Pablo</h4>
                <ul class="nav nav-pills nav-stacked">
                    <li class="active"><a href="index.php">Inicio</a></li>
                    <li><a href="css.php">CSS</a></li>
                    <li><a href="javascript.php">JAVASCRIPT</a></li>
                </ul><br>
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Buscar">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
                </br>
                 
                <a href="https://twitter.com"><img src="img/twitter.png" class="img-rounded" alt="Cinque Terre" width="90" height="90"></a>
                <a href="https://www.facebook.com"><img src="img/instagram.png" class="img-rounded" alt="Cinque Terre" width="90" height="90"></a>
                <a href="https://www.instagram.com"><img src="img/facebook.png" class="img-rounded" alt="Cinque Terre" width="90" height="90"></a>
            </div>